version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress1234
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - backend

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./public_html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    links:
      - db:mysql
    restart: always
    environment:
      WORDPRESS_DP_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - backend
volumes:
   db_data:
   public_html:
networks:
   backend:
     driver: bridge
